clf = svm.SVC(kernel='deep-kernel')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
a = accuracy_score(y_pred, y_test)
print(a)
level=list()
level.append(('svm',svm.SVC()))
level.append(('NN',Sequential()))
level1=svm.SVC()
# s=StackingClassifier(estimators=level,final_estimator=level1)
s.fit(x_train,y_train)
x=s.predict(x_test)
a=accuracy_score(x)